- src: geerlingguy.apache
  version: 1.6.0
- src: geerlingguy.mysql
  version: 1.9.1
- src: geerlingguy.php
  version: 1.8.2
- src: https://github.com/hajaalin/ansible-bookedscheduler/archive/v2.5.19_0.2.tar.gz
  name: bookedscheduler
- src: https://github.com/hajaalin/ansible-ssl-setup/archive/v0.4.0.tar.gz
  name: ssl-setup
