- src: hajaalin.bookedscheduler
- src: geerlingguy.apache
  version: 1.7.3
- src: geerlingguy.mysql
  version: 2.4.0
- src: geerlingguy.php
  version: 3.3.0
- src: jdauphant.ssl-certs
  version: v1.2.5
